config/routes.rb
require 'sidekiq/web'
require 'sidekiq-status/web'

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Graph::Engine, at: '/graph'

  authenticate :user, ->(u) { u.role == 'admin' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :actions do
    get '/', action: :index
    get '/:user_id', action: :show, as: :show
  end

  resources :calendar, controller: :calendar

  resources :channel_manager, contoller: 'channel_manager', except: [:new, :edit] do
    collection do
      post :update_prices
    end
    member do
      get :match_plans
    end
  end

  resource :company, except: [:new, :show, :destroy] do
    resources :users, only: [:index, :destroy]
  end

  resources :hotels, only: :show do
    collection do
      get :search, action: :search, as: :search
      get :markers, action: :markers, as: :markers
    end
  end

  scope 'hotels/:hotel_id', as: :hotel do
    resources :contacts
  end
  get 'hotels/contacts/by_hotel', controller: :contacts, action: :by_hotel

  resources :rooms, only: [:update] do
    put :bulk_update, on: :collection
  end

  resources :related_hotels do
    collection do
      get :search
      get :enable
      get :disable
      delete :destroy
    end
  end

  resources :reservations do
    post :search, on: :collection
    post 'notify_partner/:partner_id', action: :notify_partner, as: :notify_partner
  end

  resources :settings, only: [:index, :edit, :update]

  namespace :payments do
    get :details, action: :details
    post :update_status, action: :update_status
    get :transaction_result, action: :transaction_result

    post :modify_items, action: :modify_items
  end

  namespace :wizard do
    (1..5).to_a.each do |i|
      action = "step#{ i }".to_sym
      action_post = "step#{ i }_post".to_sym

      get "step/#{ i }", action: action, as: action, step: i
      post "step/#{ i }", action: action_post, as: action_post, step: i
    end

    get :setup_not_completed, action: :setup_not_completed, as: :setup_not_completed
  end

  root to: 'calendar#index'
  devise_for :users, controllers: {
    registrations: 'registrations',
    passwords: 'passwords',
    invitations: 'invitations',
    sessions: 'sessions'
  }
end

app/models/setting.rb
# == Schema Information
#
# Table name: settings
#
#  id                 :integer          not null, primary key
#  crawling_frequency :integer
#  stars              :text             default([]), is an Array
#  user_ratings       :text             default([]), is an Array
#  property_types     :text             default([]), is an Array
#  company_id         :integer
#  created_at         :datetime
#  updated_at         :datetime
#  districts          :text             default([]), is an Array
#  booking_page       :integer
#  page_position      :integer
#  strategy           :string
#  current_job        :string
#  sidekiq_lock       :boolean          default(FALSE)
#
# Indexes
#
#  index_settings_on_company_id  (company_id) UNIQUE
#

class Setting < ActiveRecord::Base
  CRAWLING_FREQUENCIES = [
    2.hours, 3.hours, 4.hours, 5.hours, 6.hours
  ].map(&:to_i).freeze

  STARS = (1..5).to_a.map(&:to_s).freeze

  USER_RATINGS = (0..100).to_a.map { |n| (n.to_f / 10).to_s }.freeze

  attr_accessor :user_ratings_range

  is_impressionable

  belongs_to :company

  has_many :room_settings do
    def room_hash
      each_with_object({}) do |rs, hash|
        hash[rs.room_id] = rs
      end
    end
  end

  after_create :create_room_settings

  after_update :restart_algorithm
  after_save :recreate_related_hotels

  validates_inclusion_of :crawling_frequency, within: CRAWLING_FREQUENCIES
  validates :stars, array: { inclusion: { in: STARS } }
  validates :user_ratings, array: { inclusion: { in: USER_RATINGS } }
  validates :property_types, array: { inclusion: { in: Hotel::OLD_PROPERTY_TYPES.keys } }

  def user_ratings_range
    @user_ratings_range ||
    begin
      OpenStruct.new(
        from: user_ratings.map(&:to_f).min * 10,
        to: user_ratings.map(&:to_f).max * 10
      )
    rescue
      OpenStruct.new(
        from: 1,
        to: 100
      )
    end
  end

  def user_ratings_range=(hash)
    @user_ratings_range = OpenStruct.new hash
    range = user_ratings_range.from..user_ratings_range.to
    self[:user_ratings] = range.to_a.map{ |x| (x.to_f / 10).to_s }
  end

  def lock!
    update_column(:sidekiq_lock, true)
  end

  def unlock!
    update_column(:sidekiq_lock, false)
  end

  def hotel
    company.channel_manager.hotel rescue nil
  end

  private

  def restart_algorithm
    PriceMaker::PriceWorker.perform_async(id)
  end

  def recreate_related_hotels
    if hotel.present?
      RelatedHotelsCleanerWorker.new.perform(company_id)
      hotel.amenities_calc(company_id, true)
    end
    true
  end

  def create_room_settings
    return true unless hotel.present?
    hotel.rooms.pluck(:id).each do |room_id|
      RoomSetting.find_or_create_by(room_id: room_id, setting: self) do |obj|
        obj.position = 1
      end
    end
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  load_and_authorize_resource

  def index
    setting = current_user.setting

    if can?(:update, setting)
      redirect_to [:edit, setting]
    else
      redirect_to root_path
    end
  end

  def edit
    @hotel = @setting.hotel
    company = @setting.company
    @related = ensure_related_existence(@hotel, company)

    @channel_manager = company.channel_manager

    gon.rabl template: 'app/views/hotels/show.rabl'

    @cm_rooms = begin
      @channel_manager.connector.get_rooms.name_id_mapping
    rescue ConnectorError => e
      []
    end

    @room_settings = @setting.room_settings.room_hash
  end

  def update
    @setting.attributes = settings_params

    if request.xhr?
      # for render related_hotels/edit template
      @hotel = @setting.hotel
      @related = @hotel.related_hotels.includes(:related)
    end

    if @setting.save!
      flash[:success] = I18n.t('messages.settings_updated')
      impressionist(@setting)

      force_fetch_prices_and_rooms

      redirect_to [:settings] unless request.xhr?
    else
      flash[:alert] = @setting.errors.full_messages.to_sentence
      render :edit unless request.xhr?
    end
  end

  protected

  def ensure_related_existence(hotel, company)
    begin
      hotel.related.map(&:name)
      hotels
    rescue
      hotel.related_ids = []
      hotel.amenities_calc(company.id, true)
    end
    hotel.related_hotels.includes(:related)
  end

  def force_fetch_prices_and_rooms
    cm = @setting.company.channel_manager
    cm.sync_rooms
  end

  def settings_params
    # HACK for select2 empty value
    %i(stars property_types districts).each do |field|
      if params[:setting][field].present?
        params[:setting][field].select!(&:present?)
      end
    end

    params[:setting][:user_ratings_range][:from] = params[:setting][:user_ratings_range][:from].to_i
    params[:setting][:user_ratings_range][:to] = params[:setting][:user_ratings_range][:to].to_i

    params.require(:setting).permit(:crawling_frequency, stars: [],
      property_types: [], districts: [], user_ratings_range: [:from, :to]
    )
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
  def options_for_crawling_frequencies(default = nil)
    default ||= DefaultSetting.default[:crawling_frequency]
    options = Setting::CRAWLING_FREQUENCIES.map do |time|
      [humanize(time), time]
    end

    options_for_select(options, default)
  end

  def options_for_stars(default = nil)
    default ||= DefaultSetting.default[:stars]
    options = Setting::STARS.map do |n|
      ["#{n}*", n]
    end

    options_for_select(options, default)
  end

  def options_for_properties(default = nil)
    default ||= DefaultSetting.default[:property_types]
    options = Hotel::OLD_PROPERTY_TYPES.map do |property, _id|
      [I18n.t("enum.property_type.#{property}"), property]
    end

    options_for_select(options, default)
  end

  def options_for_districts(default = nil, setting = nil)
    city = setting.present? ? setting.hotel.city : 'Prague'
    default ||= DefaultSetting.for_company(setting.company)[:districts] if setting.present?

    options_for_select(Hotel.city_districts(city), default)
  end

  def options_for_booking_id(default, hotel_id)
    hotel = Hotel.find(hotel_id)
    room_ids = BlockAvailabilityExtractor.new(BlockAvailability.for_hotels(hotel.booking_id)).room_ids

    options_for_select(room_ids, default)
  end
end

app/views/settings/_form.html.haml
.overbooking_form
  - if controller_name == 'settings'
    .h20px= t('related_hotels.edit.header')
    .description_text= t('related_hotels.edit.description').html_safe

  = form_for @setting, url: @setting, html: { class: 'form-horizontal settings-form' }, remote: true do |f|
    .inputs
      .row
        .col-xs-6
          = f.label :property_types
          = f.select :property_types,
              options_for_properties(@setting.property_types),
              { include_blank: false },
              multiple: true,
              class: 'form-control search-select'
        .col-xs-6
          = f.label :districts
          = f.select :districts,
            options_for_districts(@setting.districts, @setting),
            { include_blank: false },
            multiple: true,
            class: 'form-control search-select'

      .row
        .col-xs-6
          = f.label :stars
          = f.select :stars,
            options_for_stars(@setting.stars),
            { include_blank: false },
            multiple: true,
            class: 'form-control search-select'
          %button.btn.btn_apply{type: 'submit'}
            = icon('check')
            = t('shared.update')
        .col-xs-6
          = f.label :user_ratings
          #user-rating-slider
          = f.fields_for :user_ratings_range, f.object.user_ratings_range do |rf|
            = rf.hidden_field :from, id: 'user-rating-from'
            = rf.hidden_field :to, id: 'user-rating-to'

  %a.text_link{href: '#', data: {target: '.search-container'}}
    = icon('pencil')
    %span= t('related_hotels.index.click_to_search')
  .row.add_hotels_frm
    .hidden
      %span(data-message="select_hotels_first")= t('messages.select_hotels_first')
      %span(data-message="confirm_related_bulk_delete")= t('messages.confirm_related_bulk_delete')
      %span(data-message="related_search_prompt")= t('messages.related_search_prompt')

    = form_tag related_hotels_path(hotel_id: @hotel.booking_id), method: :post, remote: true, class: 'add-related-form' do
      .search-container.hidden
        .col-xs-9.col-md-8
          = hidden_field_tag :id, nil, id: 'add_related_select2', data: { url: search_related_hotels_path(hotel_id: @hotel.booking_id) }
        .col-xs-3.col-md-4
          = button_tag type: :submit, class: 'btn pull-right' do
            = icon('search')
            = t('related_hotels.edit.add_related')

app/views/settings/edit.html.haml
.container-fluid
  = content_for(:main_content_header) do
    .page_header.h2.light
      %span.page_header_title= t('.header')

  .tabbable
    %ul.nav.nav-tabs
      %li.active
        %a.btn{"data-toggle" => "tab", href: "#room_settings_tab"}
          %i.clip-circle-small
          = t('.room_settings')
      %li
        %a.btn{"data-toggle" => "tab", href: "#competitors_tab"}
          = t('.competitors_lookup')
      %li
        %a.btn{"data-toggle" => "tab", href: "#channel_manager_tab"}
          = t('.channel_manager')

  .tab-content
    #channel_manager_tab.tab-pane.max_width.center-block.company_form
      .h20px= t('channel_manager.edit.header')
      .separate
      = render 'channel_manager/form'
      .clearfix

    #room_settings_tab.tab-pane.active
      - if @channel_manager
        .h20px= t('channel_manager.edit.room_match_info').html_safe
      = render partial: 'rooms/form'
      .clearfix

    #competitors_tab.tab-pane
      .competitors_block.width_control
        .row
          .col-md-5
            = render 'form'
            .separate
            #results_placeholder(data-partial="related_hotels")
              = render template: 'related_hotels/edit'
          .col-md-7
            #directions-panel.hidden
            #map
      .clearfix