config/routes.rb
require 'sidekiq/web'
require 'sidekiq-status/web'

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Graph::Engine, at: '/graph'

  authenticate :user, ->(u) { u.role == 'admin' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :actions do
    get '/', action: :index
    get '/:user_id', action: :show, as: :show
  end

  resources :calendar, controller: :calendar

  resources :channel_manager, contoller: 'channel_manager', except: [:new, :edit] do
    collection do
      post :update_prices
    end
    member do
      get :match_plans
    end
  end

  resource :company, except: [:new, :show, :destroy] do
    resources :users, only: [:index, :destroy]
  end

  resources :hotels, only: :show do
    collection do
      get :search, action: :search, as: :search
      get :markers, action: :markers, as: :markers
    end
  end

  scope 'hotels/:hotel_id', as: :hotel do
    resources :contacts
  end
  get 'hotels/contacts/by_hotel', controller: :contacts, action: :by_hotel

  resources :rooms, only: [:update] do
    put :bulk_update, on: :collection
  end

  resources :related_hotels do
    collection do
      get :search
      get :enable
      get :disable
      delete :destroy
    end
  end

  resources :reservations do
    post :search, on: :collection
    post 'notify_partner/:partner_id', action: :notify_partner, as: :notify_partner
  end

  resources :settings, only: [:index, :edit, :update]

  namespace :payments do
    get :details, action: :details
    post :update_status, action: :update_status
    get :transaction_result, action: :transaction_result

    post :modify_items, action: :modify_items
  end

  namespace :wizard do
    (1..5).to_a.each do |i|
      action = "step#{ i }".to_sym
      action_post = "step#{ i }_post".to_sym

      get "step/#{ i }", action: action, as: action, step: i
      post "step/#{ i }", action: action_post, as: action_post, step: i
    end

    get :setup_not_completed, action: :setup_not_completed, as: :setup_not_completed
  end

  root to: 'calendar#index'
  devise_for :users, controllers: {
    registrations: 'registrations',
    passwords: 'passwords',
    invitations: 'invitations',
    sessions: 'sessions'
  }
end

app/models/related_hotel.rb
# == Schema Information
#
# Table name: related_hotels
#
#  id             :integer          not null, primary key
#  hotel_id       :integer
#  related_id     :integer
#  is_overbooking :boolean          default(FALSE)
#  added_manually :boolean          default(FALSE)
#
# Indexes
#
#  index_related_hotels_on_hotel_id                 (hotel_id)
#  index_related_hotels_on_related_id_and_hotel_id  (related_id,hotel_id) UNIQUE
#

class RelatedHotel < ActiveRecord::Base
  self.table_name = :related_hotels

  belongs_to :hotel
  belongs_to :related,
             foreign_key: :related_id,
             class_name: 'Hotel'

  validates_uniqueness_of :hotel_id, scope: :related_id
end

app/controllers/related_hotels_controller.rb
class RelatedHotelsController < ApplicationController
  before_filter :find_and_auth_resource
  skip_before_filter :wizard_completed

  def create
    @new_related = Hotel.where(booking_id: params[:id].split(','))

    @new_related.each do |related|
      @hotel.related_hotels << RelatedHotel.new(
        hotel: @hotel,
        related: related,
        added_manually: true
      )
    end

    list = @new_related.map(&:name).to_sentence
    flash[:success] = t('messages.success_add_related', list: list)

    # for render related_hotels/edit template
    @related = @hotel.related_hotels.includes(:related)
  end

  def enable
    update_overbooking(params, true)
  end

  def disable
    update_overbooking(params, false)
  end

  def destroy
    @related = Hotel.where(booking_id: params[:id])

    if @hotel.related.delete(@related)
      list = @related.map(&:name).to_sentence
      flash[:success] = t('messages.success_remove_related', list: list)
    end
  end

  def search
    @hotels = Hotel
      .full_text_search(params[:q])
      .where.not(booking_id: params[:id])
      .where.not(id: @hotel.related_ids)
      .where(city: @hotel.city)
      .limit(300)
  end

  protected

  def find_and_auth_resource
    hotel_id = (params[:hotel_id].nil? ? params[:id] : params[:hotel_id])
    @hotel = Hotel.accessible_by(current_ability)
                 .find_by_booking_id(hotel_id)
    authorize! :update, @hotel
  end

  def update_overbooking(params, state)
    begin
      hotel_ids = Hotel.where(booking_id: params[:ids]).pluck(:id)
      @hotel.related_hotels.where(related_id: hotel_ids).update_all(is_overbooking: state)
      render json: {success: true}
      flash[:success] = t('messages.settings_updated')
    rescue Exception => e
      render json: {status: 500}
      flash[:error] = e.message
    end
  end
end

app/views/related_hotels/create.js.erb
( function(){
    $partial = $('[data-partial="related_hotels"]');
    $partial.html("<%= escape_javascript(render template: 'related_hotels/edit') %>");
    $partial.unblock();

    Related.initSelect2RelatedSearch();

    setTimeout( function(){
        Related.initMap();
    }, 500)
})();

app/views/related_hotels/destroy.js.erb
( function(){
    var $row;
    $row = $('.related-hotels-table').find('[data-hotel-id="<%= params[:id] %>"]');
    unblockRowElement($row);
    removeRow($row);

    setTimeout( function(){
        Related.initMap();
    }, 500);
})();

app/views/related_hotels/edit.html.haml
- if @related.length > 0
  %h3.light
    = t('related_hotels.index.count', count: @related.length)

  - if @related.length > 0
    %table.table.manage_table.related-hotels-table
      %thead
        %tr
          %th Booking ID
          %th= t('related_hotels.index.hotel_name')
          %th= t('.overbooking_partnership')
          %th= t('shared.actions')
      %tbody
        - @related.limit(2).each do |related_hotel|
          %tr(data-hotel-id="#{ related_hotel.try(:related).try(:booking_id) }")
            %td= related_hotel.try(:related).try(:booking_id)
            %td
              %strong= related_hotel.try(:related).try(:name)
              - if related_hotel.added_manually
                %span.label.label-default= RelatedHotel.human_attribute_name(:added_manually)
              %br
              %small=related_hotel.try(:related).try(:post_address)
            %td
              = link_to disable_related_hotels_path(id: @hotel.booking_id, ids: related_hotel.try(:related).try(:booking_id)), remote: true, class: "btn bulk-overbooking #{related_hotel.is_overbooking ? '' : 'hidden'}" do
                = icon('trash')
                = t('.remove_partner')
              = link_to enable_related_hotels_path(id: @hotel.booking_id, ids: related_hotel.try(:related).try(:booking_id)), remote: true, class: "btn btn-success bulk-overbooking #{related_hotel.is_overbooking ? 'hidden' : ''}" do
                = icon('chain')
                = t('.become_partner')
            %td
              = link_to related_hotels_path(hotel_id: @hotel.booking_id, id: related_hotel.try(:related).try(:booking_id)), class: 'btn btn_delete remove-related', remote: true, method: :delete do
                = icon('trash')
                = t('shared.remove')

app/views/related_hotels/index.html.haml
= content_for(:main_content_header) do
  .row
    .col-sm-12
      .page-header
        %h1
          = t('.header')
          %small= t('.subheader')

.row
  .col-sm-12
    %table.table.table-hover
      %thead
        %tr
          %th= Hotel.human_attribute_name(:booking_id)
          %th= Hotel.human_attribute_name(:name)
          %th= Hotel.human_attribute_name(:address)
          %th= Hotel.human_attribute_name(:district)
          %th
      %tbody
        - @hotels.each do |hotel|
          %tr
            %td= hotel.booking_id
            %td= hotel.name
            %td= [hotel.zip, hotel.city, hotel.address].compact.join(', ')
            %td= hotel.district
            %td.center
              .visible-md.visible-lg.hidden-sm.hidden-xs
                = link_to [:edit, :related_hotel, id: hotel.booking_id],
                class: 'btn btn-xs btn-teal tooltips',
                data: { 'original-title' => t('overbooking.shared.edit') } do
                  = icon('edit')
              .visible-sm.visible-xs.hidden-md.hidden-lg
                = link_to [:edit, :related_hotel, id: hotel.booking_id],
                class: 'btn btn-xs btn-teal tooltips' do
                  = icon('edit')
    = paginate @hotels