config/routes.rb
require 'sidekiq/web'
require 'sidekiq-status/web'

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Graph::Engine, at: '/graph'

  authenticate :user, ->(u) { u.role == 'admin' } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :actions do
    get '/', action: :index
    get '/:user_id', action: :show, as: :show
  end

  resources :calendar, controller: :calendar

  resources :channel_manager, contoller: 'channel_manager', except: [:new, :edit] do
    collection do
      post :update_prices
    end
    member do
      get :match_plans
    end
  end

  resource :company, except: [:new, :show, :destroy] do
    resources :users, only: [:index, :destroy]
  end

  resources :hotels, only: :show do
    collection do
      get :search, action: :search, as: :search
      get :markers, action: :markers, as: :markers
    end
  end

  scope 'hotels/:hotel_id', as: :hotel do
    resources :contacts
  end
  get 'hotels/contacts/by_hotel', controller: :contacts, action: :by_hotel

  resources :rooms, only: [:update] do
    put :bulk_update, on: :collection
  end

  resources :related_hotels do
    collection do
      get :search
      get :enable
      get :disable
      delete :destroy
    end
  end

  resources :reservations do
    post :search, on: :collection
    post 'notify_partner/:partner_id', action: :notify_partner, as: :notify_partner
  end

  resources :settings, only: [:index, :edit, :update]

  namespace :payments do
    get :details, action: :details
    post :update_status, action: :update_status
    get :transaction_result, action: :transaction_result

    post :modify_items, action: :modify_items
  end

  namespace :wizard do
    (1..5).to_a.each do |i|
      action = "step#{ i }".to_sym
      action_post = "step#{ i }_post".to_sym

      get "step/#{ i }", action: action, as: action, step: i
      post "step/#{ i }", action: action_post, as: action_post, step: i
    end

    get :setup_not_completed, action: :setup_not_completed, as: :setup_not_completed
  end

  root to: 'calendar#index'
  devise_for :users, controllers: {
    registrations: 'registrations',
    passwords: 'passwords',
    invitations: 'invitations',
    sessions: 'sessions'
  }
end

app/models/facility/room.rb
# == Schema Information
#
# Table name: room_facilities
#
#  id    :integer          not null, primary key
#  name  :string
#  count :integer          default(0)
#
# Indexes
#
#  index_room_facilities_on_id  (id) UNIQUE
#

class Facility::Room < ActiveRecord::Base
  include FacilityMethods

  BASE_FACILITY_CACHE_KEY = 'room:base_facilities'

  has_and_belongs_to_many :rooms,
                          join_table: 'room_facilities_rooms',
                          class_name: '::Room',
                          foreign_key: 'room_facility_id',
                          association_foreign_key: 'room_id'

  after_save :clear_base_facility_cache, if: -> { Room::BASE_FACILITIES.include?(name) }

  private

  def clear_base_facility_cache
    Rails.cache.delete(BASE_FACILITY_CACHE_KEY)
  end
end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id                 :integer          not null, primary key
#  roomtype           :string
#  max_price          :float
#  min_price          :float
#  hotel_id           :integer
#  name               :string
#  channel_manager_id :integer
#  subroom            :integer
#  max_people         :integer
#  price              :float
#  booking_id         :integer
#  booking_hotel_id   :integer
#  previo_id          :integer
#  wubook_id          :integer
#
# Indexes
#
#  index_rooms_on_booking_hotel_id    (booking_hotel_id)
#  index_rooms_on_booking_id          (booking_id)
#  index_rooms_on_channel_manager_id  (channel_manager_id)
#  index_rooms_on_hotel_id            (hotel_id)
#  index_rooms_on_previo_id           (previo_id)
#  index_rooms_on_roomtype            (roomtype)
#

class Room < ActiveRecord::Base
  include RoomProperties
  include PriceMaker::RoomAmenities
  include PriceMaker::ChannelManager

  scope :contains_facilities, -> (ids) { includes(:facilities).where(room_facilities: { id: ids }) }
  scope :with_facilities, -> (ids) { contains_facilities(ids).select { |h| (ids - h.facilities.map(&:id)).size.zero? } }

  belongs_to :hotel, foreign_key: :booking_hotel_id, primary_key: :booking_id

  has_many :room_prices, dependent: :destroy
  has_many :room_settings, dependent: :destroy

  has_and_belongs_to_many :facilities,
                          class_name: 'Facility::Room',
                          association_foreign_key: 'room_facility_id' # counter as PG trigger

  has_one :bedding

  after_create :create_room_settings

  validates_numericality_of :min_price, greater_than_or_equal_to: 0
  validate :validate_max_price
  validates_uniqueness_of :booking_id, scope: :hotel_id, allow_blank: true

  def max_people_fallback
    max_people.to_i == 0 ? 1 : max_people
  end

  def name
    self[:name] || self[:roomtype].to_s + " (#{self[:max_people]} people)"
  end

  private

  def validate_max_price
    if max_price < min_price
      errors.add(:max_price, :greater_than_or_equal_to, count: min_price.to_s)
    end
  end

  def create_room_settings
    Setting.where(hotel_id: room.hotel_id).find_each do |setting|
      RoomSetting.create(
        setting: setting,
        room: self,
        position: 1
      )
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  load_and_authorize_resource except: :bulk_update # ability checking in permit method

  skip_before_filter :wizard_completed, only: :bulk_update

  def update
    unless @room.update(room_params)
      flash[:alert] = @room.errors.full_messages.to_sentence
      render none: true
    end
  end

  def bulk_update
    @rooms = Room.update(bulk_update_params.keys, bulk_update_params.values)
    if bulk_errors(@rooms).present?
      flash[:alert] = bulk_errors(@rooms)
    else
      if params[:room_settings].present?
        RoomSetting.update(bulk_update_room_settings_params.keys, bulk_update_room_settings_params.values)
      end
      if params[:manual] && params[:manual] == 'true'
        flash[:success] = t('messages.room_updated')
      end
    end
  end

  protected

  def allowed_attributes
    attributes = %i(min_price max_price)

    if can?(:update_connector_credentials, Room)
      attributes += %i(booking_id previo_id wubook_id)
    end

    attributes
  end

  def room_params
    params.require(:room).permit(*allowed_attributes)
  end

  def bulk_update_params
    params.require(:rooms).tap do |whitelisted|
      params[:rooms].each do |(room_id, attr)|
        next unless can?(:update, Room.find(room_id))
        whitelisted[room_id] = ActionController::Parameters.new(attr)
            .permit(*allowed_attributes)
      end
    end
  end

  def bulk_update_room_settings_params
    params.require(:room_settings).tap do |whitelisted|
      params[:room_settings].each do |(id, attr)|
        next unless can?(:update, RoomSetting.find(id))
        whitelisted[id] = ActionController::Parameters.new(attr).permit(:position)
      end
    end
  end

  def bulk_errors(rooms)
    rooms.map do |room|
      next if room.errors.empty?
      "<strong>#{ room.name }</strong>: #{ room.errors.full_messages.to_sentence }"
    end.compact.join('<br>')
  end
end

app/views/rooms/_form.html.haml
= form_tag bulk_update_rooms_path, method: :put, class: 'rooms-form', remote: true do
  = hidden_field_tag :manual, true
  %table.table{class: (controller_name == 'settings' ? 'setting_room_table' : 'hotel_rooms_table')}
    %thead
      %tr
        %th Booking ID
        - unless current_user.channel_manager.connector_type == 'empty'
          %th CM ID
        %th= Room.human_attribute_name(:name)
        %th= Room.human_attribute_name(:min_price)
        %th= Room.human_attribute_name(:max_price)
        - if controller_name != 'wizard'
          %th= t('settings.strategy.title')
        - if current_user.channel_manager.connector_type != 'empty' && can?(:update_connector_credentials, Room)
          %th= t('labels.select_room')
    %tbody
      - @hotel.rooms.each do |room|
        = fields_for 'rooms[]', room do |f|
          = render 'rooms/row_form', f: f
      - if controller_name == 'settings'
        %td
        %td
        %td
        %td
        - if current_user.channel_manager.connector_type != 'empty' && can?(:update_connector_credentials, Room)
          %td
          %td
        %td
          = button_tag class: 'btn btn_apply pull-right', type: :submit do
            = icon('check')
            = t('shared.save')
      - else
        %td
          = link_to wizard_step3_path, class: 'back_link pull-left' do
            = icon('arrow-left')
            = t('shared.prev')
        %td
        %td
        - if current_user.channel_manager.connector_type != 'empty' && can?(:update_connector_credentials, Room)
          %td
          %td
        %td
          = button_tag class: 'btn btn_apply pull-right', type: :submit do
            = icon('arrow-right')
            = t('shared.next')

app/views/rooms/_row_form.html.haml
%tr(data-room-id="#{ f.object.id }")
  %td= f.object.booking_id
  - unless current_user.channel_manager.connector_type == 'empty'
    %td= f.object.wubook_id || f.object.previo_id
  %td= f.object.name
  %td
    .has-feedback
      = f.number_field :min_price, class: 'form-control'
      = icon('eur form-control-feedback')
  %td.edit-price
    .has-feedback
      = f.number_field :max_price, class: 'form-control'
      = icon('eur form-control-feedback')

  - if controller_name != 'wizard'
    %td
      = fields_for 'room_settings[]', @room_settings[f.object.id] do |f|
        = f.number_field :position, class: 'form-control', min: 1, max: 100, step: 1

  - if current_user.channel_manager.connector_type != 'empty' && can?(:update_connector_credentials, Room)
    %td.edit-cm
      - case current_user.channel_manager.connector_type
      - when 'previo'
        = f.select :previo_id, options_for_select(@cm_rooms, f.object.previo_id), {include_blank: t('labels.select_room')}, class: 'form-control selectpicker'
      - when 'wubook'
        = f.select :wubook_id, options_for_select(@cm_rooms, f.object.wubook_id), {include_blank: t('labels.select_room')}, class: 'form-control selectpicker'

app/views/rooms/bulk_update.js.erb
<% @rooms.each do |room| %>
( function() {
    var $roomRow = $('tr[data-room-id="<%= room.id %>"]');

    <% if room.errors.size.zero? %>
        <% if room.previous_changes.length > 0 %>
            $roomRow.addClass('success');
            $roomRow.find('.action .success').show();

            setTimeout( function(){
                $roomRow.removeClass('success');
                $roomRow.find('.action .success').hide();
            }, 3000);
        <% end %>
    <% else %>
        $roomRow.addClass('danger');
        $roomRow.find('.action .failure').show();

        setTimeout( function(){
            $roomRow.removeClass('danger');
            $roomRow.find('.action .failure').hide();
        }, 5000);
    <% end %>
})();
<% end %>

app/views/rooms/update.js.erb
(function(){
    var inline = $('[data-room-id="<%= @room.id %>"] input[type="submit"]').parents('.form-group').find('.help-inline');

    inline.html("<%= j I18n.t('messages.room_updated') %>");

    setTimeout(function(){
        inline.html('')
    }, 2000);
})();